server:
  port: 6060

spring:

  # mysql
  datasource:
    url: jdbc:mysql://localhost:3331/db_mysql
    username: user
    password: password
    spring:
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver



custom:
  # cors
  # mode docker : http://localhost:3001
  # mode dev    : '*'
  app:
    allowedOriginsClientURL: '*'