spring:

  # profile
  profiles:
    active: dev

    # app name
  application:
    name: swagger-springboot

    # used on rabbit mq config, for allowing multiple  @bean function
  main:
    allow-bean-definition-overriding: true


  # liquibase
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml


# promotheus
# http://localhost:5050/actuator/**
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    shutdown:
      enabled: true
      info:
        env:
          enabled: true
        enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, info, health, shutdown, beans


  # SWAGGER-UI
  # http://localhost:5050/swagger-ui/index.html
  api-docs:
    enabled: true
